### ISSUE TITLE
Error when running Main.py

### ISSUE THREAD

**Issue by beyondkayne** [WaGi-Coding/mordhau-rcon-tool#4]
I have inserted all info at ServerInfo file and then call script with python 3 Main.py. That's what i got:

Traceback (most recent call last):
  File "Main.py", line 18, in <module>
    newListen()
  File "Main.py", line 16, in newListen
    listen.startListen(allowed)
  File "/home/mhservertest/MordhauRCON/listenScript.py", line 29, in startListen
    self.mcr.connect()
  File "/home/mhservertest/MordhauRCON/rojoMCRcon.py", line 62, in connect
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

Please help to fix it.

**Comment by WaGi-Coding** [comment]
idk what Rojos rcon stuff has to do with mine ^^ I am not even using python tho
